// <auto-generated />
using System;
using Hairly.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hairly.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260402181518_IntroduceAndSeedProductAndReviewEntities")]
    partial class IntroduceAndSeedProductAndReviewEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hairly.Data.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("HairdresserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("HairdresserId");

                    b.HasIndex("ServiceId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentDate = new DateTime(2025, 12, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = 1,
                            CreatedOn = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HairdresserId = "3dbb52f6-6024-4dd6-ad4b-e1c782bbd23d",
                            IsDeleted = false,
                            Note = "Първо посещение",
                            ServiceId = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            AppointmentDate = new DateTime(2025, 12, 15, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = 2,
                            CreatedOn = new DateTime(2025, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HairdresserId = "3dbb52f6-6024-4dd6-ad4b-e1c782bbd23d",
                            IsDeleted = false,
                            ServiceId = 4,
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            AppointmentDate = new DateTime(2026, 1, 5, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            ClientId = 3,
                            CreatedOn = new DateTime(2025, 12, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HairdresserId = "3dbb52f6-6024-4dd6-ad4b-e1c782bbd23d",
                            IsDeleted = false,
                            ServiceId = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            AppointmentDate = new DateTime(2026, 1, 20, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = 4,
                            CreatedOn = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HairdresserId = "3dbb52f6-6024-4dd6-ad4b-e1c782bbd23d",
                            IsDeleted = false,
                            Note = "Клиентката е много доволна от резултата",
                            ServiceId = 5,
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            AppointmentDate = new DateTime(2026, 2, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = 1,
                            CreatedOn = new DateTime(2026, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HairdresserId = "3dbb52f6-6024-4dd6-ad4b-e1c782bbd23d",
                            IsDeleted = false,
                            ServiceId = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            AppointmentDate = new DateTime(2026, 1, 25, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = 5,
                            CreatedOn = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HairdresserId = "3dbb52f6-6024-4dd6-ad4b-e1c782bbd23d",
                            IsDeleted = false,
                            Note = "Клиентът отмени заради болест",
                            ServiceId = 11,
                            Status = 2
                        },
                        new
                        {
                            Id = 7,
                            AppointmentDate = new DateTime(2026, 2, 8, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = 7,
                            CreatedOn = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HairdresserId = "3dbb52f6-6024-4dd6-ad4b-e1c782bbd23d",
                            IsDeleted = false,
                            Note = "Не се е появил и не е обадил",
                            ServiceId = 1,
                            Status = 3
                        },
                        new
                        {
                            Id = 8,
                            AppointmentDate = new DateTime(2026, 2, 18, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = 2,
                            CreatedOn = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HairdresserId = "3dbb52f6-6024-4dd6-ad4b-e1c782bbd23d",
                            IsDeleted = false,
                            ServiceId = 7,
                            Status = 0
                        },
                        new
                        {
                            Id = 9,
                            AppointmentDate = new DateTime(2026, 2, 20, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            ClientId = 6,
                            CreatedOn = new DateTime(2026, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HairdresserId = "3dbb52f6-6024-4dd6-ad4b-e1c782bbd23d",
                            IsDeleted = false,
                            Note = "Иска да свали 5см и да оформи бретон",
                            ServiceId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 10,
                            AppointmentDate = new DateTime(2026, 2, 22, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = 8,
                            CreatedOn = new DateTime(2026, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HairdresserId = "3dbb52f6-6024-4dd6-ad4b-e1c782bbd23d",
                            IsDeleted = false,
                            Note = "Първи път балеаж - покажи примери",
                            ServiceId = 6,
                            Status = 0
                        },
                        new
                        {
                            Id = 11,
                            AppointmentDate = new DateTime(2026, 2, 25, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = 4,
                            CreatedOn = new DateTime(2026, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HairdresserId = "3dbb52f6-6024-4dd6-ad4b-e1c782bbd23d",
                            IsDeleted = false,
                            ServiceId = 8,
                            Status = 0
                        },
                        new
                        {
                            Id = 12,
                            AppointmentDate = new DateTime(2026, 2, 28, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            ClientId = 10,
                            CreatedOn = new DateTime(2026, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HairdresserId = "3dbb52f6-6024-4dd6-ad4b-e1c782bbd23d",
                            IsDeleted = false,
                            Note = "Само почистване на краищата",
                            ServiceId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 13,
                            AppointmentDate = new DateTime(2026, 3, 5, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            ClientId = 3,
                            CreatedOn = new DateTime(2026, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HairdresserId = "3dbb52f6-6024-4dd6-ad4b-e1c782bbd23d",
                            IsDeleted = false,
                            ServiceId = 11,
                            Status = 0
                        },
                        new
                        {
                            Id = 14,
                            AppointmentDate = new DateTime(2026, 3, 8, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = 9,
                            CreatedOn = new DateTime(2026, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HairdresserId = "3dbb52f6-6024-4dd6-ad4b-e1c782bbd23d",
                            IsDeleted = false,
                            ServiceId = 1,
                            Status = 0
                        });
                });

            modelBuilder.Entity("Hairly.Data.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HairdresserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("HairdresserId");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2024, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ivan.petrov@example.com",
                            FirstName = "Иван",
                            HairdresserId = "3dbb52f6-6024-4dd6-ad4b-e1c782bbd23d",
                            IsDeleted = false,
                            LastName = "Петров",
                            Note = "Предпочита късо подстригване, алергия към силни парфюми",
                            PhoneNumber = "+359888123456"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2024, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "maria.georgieva@example.com",
                            FirstName = "Мария",
                            HairdresserId = "3dbb52f6-6024-4dd6-ad4b-e1c782bbd23d",
                            IsDeleted = false,
                            LastName = "Георгиева",
                            Note = "Алергия към амоняк - използвай безамонячна боя",
                            PhoneNumber = "0877654321"
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2024, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "georgi.ivanov@gmail.com",
                            FirstName = "Георги",
                            HairdresserId = "3dbb52f6-6024-4dd6-ad4b-e1c782bbd23d",
                            IsDeleted = false,
                            LastName = "Иванов",
                            PhoneNumber = "0898765432"
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2025, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "elena.dimitrova@abv.bg",
                            FirstName = "Елена",
                            HairdresserId = "3dbb52f6-6024-4dd6-ad4b-e1c782bbd23d",
                            IsDeleted = false,
                            LastName = "Димитрова",
                            Note = "Предпочита топли тонове при боядисване",
                            PhoneNumber = "+359887111222"
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Петър",
                            HairdresserId = "3dbb52f6-6024-4dd6-ad4b-e1c782bbd23d",
                            IsDeleted = false,
                            LastName = "Стоянов",
                            PhoneNumber = "0878333444"
                        },
                        new
                        {
                            Id = 6,
                            CreatedOn = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "anna.todorova@mail.bg",
                            FirstName = "Анна",
                            HairdresserId = "3dbb52f6-6024-4dd6-ad4b-e1c782bbd23d",
                            IsDeleted = false,
                            LastName = "Тодорова",
                            Note = "Много чувствителен скалп - внимавай с температурата",
                            PhoneNumber = "+359899555666"
                        },
                        new
                        {
                            Id = 7,
                            CreatedOn = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Димитър",
                            HairdresserId = "3dbb52f6-6024-4dd6-ad4b-e1c782bbd23d",
                            IsDeleted = false,
                            LastName = "Василев",
                            PhoneNumber = "0877777888"
                        },
                        new
                        {
                            Id = 8,
                            CreatedOn = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sofia.nikolova@yahoo.com",
                            FirstName = "София",
                            HairdresserId = "3dbb52f6-6024-4dd6-ad4b-e1c782bbd23d",
                            IsDeleted = false,
                            LastName = "Николова",
                            Note = "Винаги иска съвет за нови прически",
                            PhoneNumber = "+359888999000"
                        },
                        new
                        {
                            Id = 9,
                            CreatedOn = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Стефан",
                            HairdresserId = "3dbb52f6-6024-4dd6-ad4b-e1c782bbd23d",
                            IsDeleted = false,
                            LastName = "Йорданов",
                            PhoneNumber = "0898111222"
                        },
                        new
                        {
                            Id = 10,
                            CreatedOn = new DateTime(2026, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "viki.hristova@gmail.com",
                            FirstName = "Виктория",
                            HairdresserId = "3dbb52f6-6024-4dd6-ad4b-e1c782bbd23d",
                            IsDeleted = false,
                            LastName = "Христова",
                            Note = "Дълга коса, иска да запази дължината",
                            PhoneNumber = "+359877333555"
                        });
                });

            modelBuilder.Entity("Hairly.Data.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Професионален шампоан за увредена коса с възстановяващо действие и незабавен ефект на заглаждане.",
                            ImageUrl = "/images/products/loreal-absolut-repair-shampoo.jpg",
                            IsDeleted = false,
                            Name = "L'Oreal Serie Expert Absolut Repair Shampoo",
                            Price = 29.90m,
                            QuantityInStock = 50
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2025, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Подсилващ шампоан за слаба и увредена коса, който възстановява структурата и здравината.",
                            ImageUrl = "/images/products/kerastase-shampoo.jpg",
                            IsDeleted = false,
                            Name = "Kerastase Resistance Bain Force Architecte Shampoo",
                            Price = 39.90m,
                            QuantityInStock = 40
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2025, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Подхранващ шампоан за суха и изтощена коса с дълбоко хидратиращ ефект.",
                            ImageUrl = "/images/products/wella-invigo-shampoo.jpg",
                            IsDeleted = false,
                            Name = "Wella Invigo Nutri-Enrich Shampoo",
                            Price = 24.50m,
                            QuantityInStock = 60
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Възстановяващ шампоан с веган кератин за силно увредена коса.",
                            ImageUrl = "/images/products/schwarzkopf-bcbonacure-shampoo.jpg",
                            IsDeleted = false,
                            Name = "Schwarzkopf BC Bonacure Repair Rescue Shampoo",
                            Price = 22.90m,
                            QuantityInStock = 55
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Дълбоко възстановяваща маска за силно увредена коса, която възвръща еластичността и блясъка.",
                            ImageUrl = "/images/products/kerastase-masque.jpg",
                            IsDeleted = false,
                            Name = "Kerastase Masque Therapiste",
                            Price = 54.90m,
                            QuantityInStock = 30
                        },
                        new
                        {
                            Id = 6,
                            CreatedOn = new DateTime(2025, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Професионална маска за интензивно възстановяване и подхранване на косата.",
                            ImageUrl = "/images/products/loreal-absolut-repair-mask.jpg",
                            IsDeleted = false,
                            Name = "L'Oreal Absolut Repair Golden Mask",
                            Price = 34.90m,
                            QuantityInStock = 45
                        },
                        new
                        {
                            Id = 7,
                            CreatedOn = new DateTime(2025, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Интензивна маска за възстановяване на косата и защита от накъсване.",
                            ImageUrl = "/images/products/wella-fusion-mask.jpg",
                            IsDeleted = false,
                            Name = "Wella Fusion Intense Repair Mask",
                            Price = 29.90m,
                            QuantityInStock = 35
                        },
                        new
                        {
                            Id = 8,
                            CreatedOn = new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Силен фиксиращ продукт с матов ефект за оформяне на модерни прически.",
                            ImageUrl = "/images/products/american-crew.jpg",
                            IsDeleted = false,
                            Name = "American Crew Fiber",
                            Price = 21.90m,
                            QuantityInStock = 50
                        },
                        new
                        {
                            Id = 9,
                            CreatedOn = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Гел със силна фиксация за структурирани и дълготрайни прически.",
                            ImageUrl = "/images/products/loreal-tecni-art.jpg",
                            IsDeleted = false,
                            Name = "L'Oreal Tecni Art Fix Max Gel",
                            Price = 19.90m,
                            QuantityInStock = 40
                        },
                        new
                        {
                            Id = 10,
                            CreatedOn = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Матираща пудра за придаване на обем и текстура на косата.",
                            ImageUrl = "/images/products/schwarzkopf-osis-dust-it.jpg",
                            IsDeleted = false,
                            Name = "Schwarzkopf Osis+ Dust It",
                            Price = 18.50m,
                            QuantityInStock = 60
                        },
                        new
                        {
                            Id = 11,
                            CreatedOn = new DateTime(2026, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Лак за коса със силна фиксация за дълготраен контрол и завършен стил.",
                            ImageUrl = "/images/products/wella-eimi-spray.jpg",
                            IsDeleted = false,
                            Name = "Wella EIMI Super Set Spray",
                            Price = 17.90m,
                            QuantityInStock = 70
                        });
                });

            modelBuilder.Entity("Hairly.Data.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("ClientId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentId = 1,
                            ClientId = 1,
                            Comment = "Много съм доволен! Бързо и качествено обслужване.",
                            CreatedOn = new DateTime(2025, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Rating = 5
                        },
                        new
                        {
                            Id = 2,
                            AppointmentId = 2,
                            ClientId = 2,
                            Comment = "Цветът стана страхотен, но отне малко повече време.",
                            CreatedOn = new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Rating = 4
                        },
                        new
                        {
                            Id = 3,
                            AppointmentId = 3,
                            ClientId = 3,
                            Comment = "Перфектно подстригване, точно както го исках.",
                            CreatedOn = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Rating = 5
                        },
                        new
                        {
                            Id = 4,
                            AppointmentId = 4,
                            ClientId = 4,
                            Comment = "Най-добрият балеаж, който съм имала!",
                            CreatedOn = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Rating = 5
                        },
                        new
                        {
                            Id = 5,
                            AppointmentId = 5,
                            ClientId = 1,
                            Comment = "Отново съм доволен, ще посетя пак.",
                            CreatedOn = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Rating = 4
                        });
                });

            modelBuilder.Entity("Hairly.Data.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DurationInMinutes")
                        .HasColumnType("int");

                    b.Property<string>("HairdresserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("DECIMAL(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("HairdresserId");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Класическо мъжко подстригване с машинка и ножица",
                            DurationInMinutes = 30,
                            HairdresserId = "3dbb52f6-6024-4dd6-ad4b-e1c782bbd23d",
                            IsDeleted = false,
                            Name = "Подстригване - мъже",
                            Price = 25.00m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Подстригване и оформяне на къса коса",
                            DurationInMinutes = 40,
                            HairdresserId = "3dbb52f6-6024-4dd6-ad4b-e1c782bbd23d",
                            IsDeleted = false,
                            Name = "Подстригване - жени (къса коса)",
                            Price = 30.00m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Подстригване и оформяне на дълга коса",
                            DurationInMinutes = 60,
                            HairdresserId = "3dbb52f6-6024-4dd6-ad4b-e1c782bbd23d",
                            IsDeleted = false,
                            Name = "Подстригване - жени (дълга коса)",
                            Price = 40.00m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Пълно боядисване с професионална боя",
                            DurationInMinutes = 120,
                            HairdresserId = "3dbb52f6-6024-4dd6-ad4b-e1c782bbd23d",
                            IsDeleted = false,
                            Name = "Боядисване - цяла глава",
                            Price = 80.00m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Частично освежаване с кичури - фолио техника",
                            DurationInMinutes = 90,
                            HairdresserId = "3dbb52f6-6024-4dd6-ad4b-e1c782bbd23d",
                            IsDeleted = false,
                            Name = "Кичури (фолио)",
                            Price = 60.00m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Балеаж техника за естествен ефект",
                            DurationInMinutes = 150,
                            HairdresserId = "3dbb52f6-6024-4dd6-ad4b-e1c782bbd23d",
                            IsDeleted = false,
                            Name = "Балеаж",
                            Price = 100.00m
                        },
                        new
                        {
                            Id = 7,
                            Description = "Измиване, подсушаване и оформяне със сешоар",
                            DurationInMinutes = 30,
                            HairdresserId = "3dbb52f6-6024-4dd6-ad4b-e1c782bbd23d",
                            IsDeleted = false,
                            Name = "Сешоар",
                            Price = 20.00m
                        },
                        new
                        {
                            Id = 8,
                            Description = "Изправяне с преса за гладка коса",
                            DurationInMinutes = 45,
                            HairdresserId = "3dbb52f6-6024-4dd6-ad4b-e1c782bbd23d",
                            IsDeleted = false,
                            Name = "Преса",
                            Price = 25.00m
                        },
                        new
                        {
                            Id = 9,
                            Description = "Къдрене с маша или ролки",
                            DurationInMinutes = 50,
                            HairdresserId = "3dbb52f6-6024-4dd6-ad4b-e1c782bbd23d",
                            IsDeleted = false,
                            Name = "Къдрене",
                            Price = 30.00m
                        },
                        new
                        {
                            Id = 10,
                            Description = "Подстригване за деца до 12 години",
                            DurationInMinutes = 20,
                            HairdresserId = "3dbb52f6-6024-4dd6-ad4b-e1c782bbd23d",
                            IsDeleted = false,
                            Name = "Детско подстригване",
                            Price = 15.00m
                        },
                        new
                        {
                            Id = 11,
                            Description = "Подстригване и оформяне на брада и мустаци",
                            DurationInMinutes = 20,
                            HairdresserId = "3dbb52f6-6024-4dd6-ad4b-e1c782bbd23d",
                            IsDeleted = false,
                            Name = "Оформяне на брада",
                            Price = 15.00m
                        },
                        new
                        {
                            Id = 12,
                            Description = "Кератиново изправяне за дълготрайна гладкост",
                            DurationInMinutes = 180,
                            HairdresserId = "3dbb52f6-6024-4dd6-ad4b-e1c782bbd23d",
                            IsDeleted = false,
                            Name = "Кератинова терапия",
                            Price = 150.00m
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "3dbb52f6-6024-4dd6-ad4b-e1c782bbd23d",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a9545bd5-d9a5-4e33-a9e3-14a174654fe1",
                            Email = "stylist@hairly.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "STYLIST@HAIRLY.COM",
                            NormalizedUserName = "STYLIST@HAIRLY.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECIHtEoApQQDtY18/Iv1FNc58JIm+Pqy5z72V90CQtu3TUc7m3AcR7wI3Qhhb88jRQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "562bc431-6712-4380-946e-476d07e49db4",
                            TwoFactorEnabled = false,
                            UserName = "stylist@hairly.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Hairly.Data.Models.Appointment", b =>
                {
                    b.HasOne("Hairly.Data.Models.Client", "Client")
                        .WithMany("Appointments")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "Hairdresser")
                        .WithMany()
                        .HasForeignKey("HairdresserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hairly.Data.Models.Service", "Service")
                        .WithMany("Appointments")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Hairdresser");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Hairly.Data.Models.Client", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "Hairdresser")
                        .WithMany()
                        .HasForeignKey("HairdresserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hairdresser");
                });

            modelBuilder.Entity("Hairly.Data.Models.Review", b =>
                {
                    b.HasOne("Hairly.Data.Models.Appointment", "Appointment")
                        .WithMany("Reviews")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hairly.Data.Models.Client", "Client")
                        .WithMany("Reviews")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Hairly.Data.Models.Service", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "Hairdresser")
                        .WithMany()
                        .HasForeignKey("HairdresserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hairdresser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hairly.Data.Models.Appointment", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Hairly.Data.Models.Client", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Hairly.Data.Models.Service", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
